apiVersion: v1
kind: Service
metadata:
  name: k8s-go-reporter
  namespace: k8s-reporter
  labels:
    app: k8s-go-reporter
spec:
  type: ClusterIP
  selector:
    app: k8s-go-reporter
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
    protocol: TCP
